# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml
logo: /images/upload/logo.png
# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
  - category
  - tagcloud
  - archive

# widget behavior
archive_type: 'monthly'
show_count: false
ribbon_flow: true
# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /images/upload/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
