# Header
menu:
  首页:
    icon: icon-home
    link: /
  归档:
    icon: icon-archives
    link: /archives
  关于:
    icon: icon-exclamation
    link: /p/about.html
rss: /atom.xml
logo: /images/upload/logo.png
# Content
excerpt_link: 阅读全文>>
fancybox: true

# Sidebar
sidebar: right
widgets:
  - personal
  # - category
  # - tag
  # - tagcloud
  # - archive
  # - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
# index_widgets:
#   - category
#   - tagcloud
#   - archive

personal:
  avatar: /images/upload/avatar.png
  name: JJ Xie
  description: 一位头发乌黑浓密，不穿格子衫，长得还帅的程序员.

lines:
  标签:
    icon: icon-tags
    link: /tags
  分类:
    icon: icon-category
    link: /categories
  XFun:
    icon: icon-github
    link: https://github.com/jianjunx/hexo-theme-xfun

icons:
  GitHub:
    icon: icon-github
    link: https://github.com/jianjunx
  微博:
    icon: icon-weibo
    link: https://weibo.com/autoshun
  知乎:
    icon: icon-zhihu
    link: /
  掘金:
    icon: icon-juejin
    link: /

# 评论
valine:
  appId: "pzmKEXwktJcbFThJyEK0HiUt-9Nh9j0Va"
  appKey: "hBrXSEpHp0MSCNHQNpcFfi7J"

# widget behavior
archive_type: "monthly"
show_count: true
ribbon_flow: true

# favicon.ico
favicon: /images/upload/favicon.png

# 右上角GitHub
github: https://github.com/jianjunx/jianjun-fun