# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: serverless CI

on:
  [repository_dispatch, workflow_dispatch]
  # repository_dispatch:
  #   types: [start, opened, deleted]
  # workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
          npm install -g hexo-cli

      - name: Sync yuque
        env:
          YUQUE_TOKEN: ${{secrets.YUQUE_TOKEN}}
          COS_SECRETID: ${{ secrets.TENCENT_SECRET_ID }}
          COS_SECRETKEY: ${{ secrets.TENCENT_SECRET_KEY }}
        run: npm run sync

      - name: Build hexo
        run: npm run build

      - name: Deploy hexo
        run: hexo deploy user=${{ secrets.FTP_USER }} password=${{secrets.FTP_PWD}}

      # - name: Serverless deploy
      #   env: # Or as an environment variable
      #     STAGE: prod
      #     SERVERLESS_PLATFORM_VENDOR: tencent
      #     TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
      #     TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
      #   run: npm run deploy:sls

      # - name: FTP-Deploy-Action
      #   uses: SamKirkland/FTP-Deploy-Action@3.1.1
      #   with:
      #     ftp-server: ftp://vhost140.cloudvhost.top:21/WEB
      #     ftp-username: ${{ secrets.FTP_USER }}
      #     ftp-password: ${{ secrets.FTP_PWD }}
      #     git-ftp-args: --insecure
      # local-dir: public

      - name: Commit
        run: |
          git config --global user.email jj.xie@outlook.com
          git config --global user.name JJXIE
          git add .
          git commit -m "update" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
